#Variables
@baseUrl = http://localhost:3333


#Heat check
# @name getHealth
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

#Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Description"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

#Get room questions
# @name getQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###


#Create question
# @name createQuestion
POST {{baseUrl}}/rooms/8b079b93-9e74-4512-afcb-21a6d18a3a62/questions
Content-Type: application/json


{
  "question": "Oque  é react?"
}

